#!/bin/bash
apt-get update 
apt-get install -y --force-yes  vim git unzip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev python-pip software-properties-common jq
apt-add-repository ppa:ansible/ansible
apt-get update
apt-get install -y --force-yes ansible

#install robotframework, python-openstackclient
pip install robotframework
pip install python-openstackclient


#install terraform
cd /tmp/files/
unzip /tmp/files/terraform_0.11.11_linux_amd64.zip
mv /tmp/files/terraform /usr/bin/.

#install the openstack terraform plugins
tar xvzf openstack_plugin.tar.gz 
mv  linux_amd64 /opt/openstack_plugin

#install the terraform inventory
tar xvzf terraform-inventory_linux_x64.tar.gz
mv terraform-inventory /usr/bin/.


#clean
apt-get -y autoremove 
apt-get -y clean 
rm -rf /root/.cache
